const Router = require('express')
const router = new Router()
const controller = require('../controllers/user')
const authMiddleware = require('../middleware/authMiddleware')
router.post('/registration', authMiddleware, controller.create)
router.get('/login', controller.login)
router.get('/refresh', controller.refresh)
router.get('/users/pages', authMiddleware, controller.getPages)
router.get('/users', authMiddleware, controller.get)
router.get('/users/:id', authMiddleware, controller.getOne)
router.put('/users/:id', authMiddleware, controller.update)
router.put('/changepassword/:id', authMiddleware, controller.password)
router.delete('/users/:id', authMiddleware, controller.delete)
module.exports = router